### PR TITLE
feat: Acknowledge basic templates

### PR DESCRIPTION
**Pull request by kulak91**
### Issue: 

https://github.com/CircleCI-Public/slack-orb/issues/366

### CODE REVIEW

**Comment by EricRibeiro** [comment]
Hi, @kulak91 👋 

I appreciate the contribution! Would you mind pushing your change without changing the JSON formatting? This will make it easier to review the PR and for future us to quickly see what was changed.

**Comment by KyleTryon** [comment]
^ That said, let's reformat the JSON right after, this is much easier to read, I'm not sure if maybe we never formatted it before? We'll figure that out separately.

**Comment by EricRibeiro** [comment]
> ^ That said, let's reformat the JSON right after, this is much easier to read, I'm not sure if maybe we never formatted it before? We'll figure that out separately.

Yea. You can rebase and separate this PR into two commits — the first with the changes necessary to support the new feature and the second with the proper formatting.

This way, we can easily see what changed and have pretty formatting.

**Comment by kulak91** [comment]
@EricRibeiro, @KyleTryon  
My sincere apologize, guys. Had a long working day and feeling a bit dizzy.  All i added is 4 lines of code (1 in each file), but for some reason JSON sometimes has weird indentation while being pushed to remote. I could create a new PR if you don't mind.

**Comment by EricRibeiro** [comment]
> @EricRibeiro, @KyleTryon My sincere apologize, guys. Had a long working day and feeling a bit dizzy. All i added is 4 lines of code (1 in each file), but for some reason JSON sometimes has weird indentation while being pushed to remote. I could create a new PR if you don't mind.

No problem. Feel free to open another PR.

Hope you get some rest and feel better soon!

**Comment by kulak91** [comment]
@EricRibeiro , looks cleaner now. 
P.s. slack orb is so convenient and easy to use. Thank you for this feature. Had fun playing with it

**Comment by EricRibeiro** [comment]
Hmm, Slack is complaining about the template format: https://app.circleci.com/pipelines/github/CircleCI-Public/slack-orb/1236/workflows/76df672a-2b24-4af7-9be9-7afe16bbcc5f/jobs/5089?invite=true#step-106-206

I don't think that's a valid property.

**Comment by kulak91** [comment]
@EricRibeiro , replaced with more appropriate blocks

**Comment by EricRibeiro** [comment]
I see you replaced `callback_id` with `action_id`. Testing in the block builder that change did the trick.

- [callback_id](https://app.slack.com/block-kit-builder/T02519B3Z#%7B%22blocks%22:%5B%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22callback_id%22:%22basic_success_view%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Farmhouse%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22%7D%5D%7D%5D%7D):
image


- [action_id](https://app.slack.com/block-kit-builder/T02519B3Z#%7B%22blocks%22:%5B%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22button%22,%22action_id%22:%22basic_success_view%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Farmhouse%22,%22emoji%22:true%7D,%22value%22:%22click_me_123%22%7D%5D%7D%5D%7D):
image

**Comment by kulak91** [comment]
Correct. Because it is an 'actions' block.  I recently worked in my project with confirmations buttons, they require callback_id, pardon messed a bit.

**Comment by EricRibeiro** [comment]
> Correct. Because it is an 'actions' block. I recently worked in my project with confirmations buttons, they require callback_id this is why automatically inserted them, pardon messed a bit.

It's all good. It's working perfectly now.

**Review by EricRibeiro — APPROVED** [review]
Thanks again! 🙇

**Comment by kulak91** [comment]
@EricRibeiro  Thank you for so fast and professional feedback. I wish all the best to you and your project.

**Comment by bear** [comment]
💛 approved

**Pull request merged**
