### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 7wikd**
### Checklist

- [ ] All new jobs, commands, executors, parameters have descriptions
- [ ] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues
Attempted to make the README.md much more appealing
### Description
Edited README.md to accommodate phrases.

### CODE REVIEW

**Comment by KyleTryon** [comment]
@7wikd Could I bother you to send over a dummy commit of some kind? We had an issue with our tests that I hope to have resolved but need to retrigger the workflow with a new commit to this branch. thank you!

**Comment by 7wikd** [comment]
In that case, would you mind if I add simply 'abc' to the commit?

**Comment by KyleTryon** [comment]
Forcefully merging for now as this is only the readme file. There seems to be some bug in this pipeline preventing an env var from being accessed. We will look into this. Thank you!

**Comment by 7wikd** [comment]
Thanks a lot!

**Pull request merged**
