### PR TITLE
Filter patterns by current branch and/or current tag [semver:minor]

### LINKED ISSUE #192: No notification is sent with empty branch name
## Orb version:

4.0.1

## What happened:

On tag push release, branch name is set empty; default regex pattern /.+/  does not match and no notification is sent.

Preparing environment variables

```
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-5f872c9e54f5364a376525ef-0-build
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=  # EMPTY HERE
  CIRCLE_BUILD_NUM=674
   ...
  CIRCLE_STAGE=release
  CIRCLE_TAG=v1.0.0
  ...
```

Final message

```
Checking For JQ + CURL: Debian
NO SLACK ALERT

Current branch does not match any item from the "branch_pattern" parameter
Current branch: 
CircleCI received exit code 0
```

## Expected behavior:

Notification should always be sent, even if branch is empty.
I believe the default `branch_pattern` should be `.*` instead of `.+`

## Additional Information:

https://github.com/CircleCI-Public/slack-orb/blob/v4.0.1/src/commands/notify.yml#L23-L27

### PR DESCRIPTION
**Pull request by skyeagle**
Added a filter pattern by the current tag.

Closes #192 and #187

### CODE REVIEW

**Review by gmemstr — DISMISSED** [review]
Debating whether to mark this as a minor or patch semver. Looks good otherwise!

**Comment by KyleTryon** [comment]
Wondering if we should break out tag into its own parameter as mentioned here: https://github.com/CircleCI-Public/slack-orb/issues/187

**Comment by skyeagle** [comment]
Is there a particular reason for having a separate parameter for tag_pattern? Looks like the regexp condition is flexible enough. What do you guys think?

**Comment by BeyondEvil** [comment]
+1 on having a separate parameter for tags, and the parameter should be regex enabled (not just true/false).

For reusability reasons, there can be multiple workflows with different tag-patterns using the same job/command.

**Comment by skyeagle** [comment]
I've updated it with a separate pattern for the current tag. Thanks!

**Comment by BeyondEvil** [comment]
Since they are mutually exclusive, is it worth having a check for that? Or at least put it in the description? Save a newbie some headache in the future. 😂

**Comment by skyeagle** [comment]
good point @BeyondEvil, I've updated the readme. thanks for the review!

**Comment by KyleTryon** [comment]
For posix compliance (to make the alpine users happy), could we swap out this bash if statement with the shell equivalent?
https://app.circleci.com/pipelines/github/CircleCI-Public/slack-orb/690/workflows/32aae1cc-acbd-4bfd-9b1a-ec0892a34d69/jobs/2475

BASH

```
if [[ -z $1 || -z $2 ]]
```

SHELL

```
if [ -z $1 ] || [ -z $2 ]
```

I want to run some additional tests here manually as well. Im not sure for instance, but I believe currently the branch filter might also match no branch at all, like there would be if it was a tagged commit.

**Comment by skyeagle** [comment]
@KyleTryon thanks for pointing out, I've made suggested changes.

**Comment by BeyondEvil** [comment]
> I want to run some additional tests here manually as well. Im not sure for instance, but I believe currently the branch filter might also match no branch at all, like there would be if it was a tagged commit.

I tried that, but it doesn't match no branch (empty string). But please try it yourself.

**Comment by skyeagle** [comment]
any chance we can merge this? It's a real showstopper for my team.

**Comment by gmemstr** [comment]
I feel comfortable with the PR right now, but I'll let @KyleTryon have the final say :)

**Comment by KyleTryon** [comment]
Merging after #202. 202 is a patch, this release will go out as a minor (for the new feature)

**Review by KyleTryon — APPROVED** [review]
Looking good 👍  releasing as a minor update.

**Pull request merged**
