### PR TITLE
[feat] include curl response in CI output [semver:patch]

### PR DESCRIPTION
**Pull request by JohnMahowald**
See https://github.com/CircleCI-Public/slack-orb/issues/194

I found it challenging to debug the permission issues I experienced when integrating with the `slack-orb` notify command. I believe including the `curl` output in the console, or parsing the response and showing a helpful error  in the CI console may be worth considering.

Lemme know what you think. Many thanks 🙏

### CODE REVIEW

**Comment by gmemstr** [comment]
I definitely think this is worth adding, but the response from Slack can be a bit verbose - we can probably take advantage of `jq`, which is already installed, to pretty print relevant parts of the response.

**Comment by JohnMahowald** [comment]
@gmemstr Thanks for the recommendation. I was feeling a little lazy and didn't want to learn how to use `jq` 🤫

Anyhow, have a look and let me know what you think. Here are the expected outputs:

Success:
```
{
  "ok": true,
  "error": null
}
```

Error:
```
{
  "ok": false,
  "error": "not_in_channel"
}
```

**Comment by gmemstr** [comment]
Looks good to me - @KyleTryon would love your :eyes: regarding the formatting.

**Comment by KyleTryon** [comment]
That looks great 👍  I think it's a great addition that keeps the output clean but improves the usefulness. Approving this for a patch update.

**Review by KyleTryon — APPROVED** [review]

**Pull request merged**
