### PR TITLE
Add option to show branch in Slack message. Based on work from @Gabri…

### PR DESCRIPTION
**Pull request by campbecf**
### Checklist
* [x]  All new jobs, commands, executors, parameters have descriptions
* [ ]  Examples have been added for any significant new features
* [ ]  README has been updated, if necessary

### Motivation, issues
Show the branch in which the job has been failed or successful is helpful if you have the same jobs across different branch

### Description
Just add the **job_branch_field** as parameter and print it as part of the slack message in the curl command in the different **commands** files

### CODE REVIEW

**Comment by campbecf** [comment]
Trying to fix the linting issues in https://github.com/CircleCI-Public/slack-orb/pull/138

**Comment by campbecf** [comment]
I have no idea what to do about that build failure.

**Comment by owenallenaz** [comment]
This would be very helpful. In the old circle-ci UI we could specify a room to send slack notifications, but since that feature doesn't exist in the new UI we have to use the slack orb to send notifications, but it's defaults are far inferior to the old-UI's default notifications.

Old:

```
Success: owenallenaz's workflow (workflow) in simpleviewinc/sv-auth (qa)
- Merge pull request #111 from mkes99/Whitelist-mint (31dd11d by owenallenaz)
```

New:

```
:tada: A build job has succeeded!
Project
cms-admin
Job Number
40
```

We've lost a lot of meaningful info with the change.

**Comment by KyleTryon** [comment]
Hello all!

Slack orb V4 is out NOW! and supports all kinds of custom messaging. Check out the new release here: https://circleci.com/developer/orbs/orb/circleci/slack

and our Wiki which will go over sending customized messages.
https://github.com/CircleCI-Public/slack-orb/wiki

**Pull request closed without merging**
