### PR TITLE
revert: revert changes introduced in `v4.12.2`

### PR DESCRIPTION
**Pull request by EricRibeiro**
## Description:

This PR rolls back the change introduced in commit b1d05c0b72b23efb7b42d157fd511b453fd874af. After investigating an issue brought to our attention on https://github.com/CircleCI-Public/slack-orb/issues/403, we learned that self-hosted runners were not updated with the `circleci env subst` CLI command.

To avoid potential issues with self-hosted runners, we have decided to roll back the change and prioritize rolling out the CLI update to our self-hosted runners.  We apologize for any inconvenience this may cause and appreciate your understanding.

Thank you for your attention and please don't hesitate to reach out if you have any questions or concerns.

### CODE REVIEW

**Comment by wyardley** [comment]
(side note: if you're using conventional commits, may want to use type `revert` vs `fix`).

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=dev:2058c87fb24a4988baf1e468e520f6f993ac026a

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=dev:2058c87fb24a4988baf1e468e520f6f993ac026a

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=4.12.3

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/slack?version=dev:2058c87fb24a4988baf1e468e520f6f993ac026a

**Pull request merged**
