### PR TITLE
Remove $SHELL check and prefer run option

### PR DESCRIPTION
**Pull request by zzak**
I found this in combination with `apk add bash curl` works on alpine based images.

### CODE REVIEW

**Comment by iynere** [comment]
@zzak why not just add `apk add bash curl` to the orb source itself in that case ?

i don't quite see what this changes—folks who don't have bash installed will still see failures; it's only the nature of the failure that will be different (`run` step will fail if `shell:` is set to a shell that isn't installed, vs. a manual `exit code 1` that actually tells users what happened)...

**Comment by iynere** [comment]
i guess i don't see how this helps the orb work w/ alpine images @zzak installing bash in your config fiile should also enable the orb to work w/ those images as-is.... or were you finding that even after installing bash, the `run` steps would still default to `sh` when the orb is used w/ alpine-based images ?

**Comment by iynere** [comment]
ahhh, i see 😄 this seems like a good fix then ! @zzak

**Comment by iynere** [comment]
how's it now ? @zzak 

i split the difference

**Comment by zzak** [comment]
@iynere LGTM, thank you for your help on this!

**Pull request merged**
