### PR TITLE
workflow success template

### PR DESCRIPTION
**Pull request by bzumby**
added workflow success template to cover popular case: https://support.circleci.com/hc/en-us/articles/360047082992-Send-slack-notification-at-end-of-workflow

### CODE REVIEW

**Comment by dsayling** [comment]
A success template was recently added in #239 - does this cover something else I might be missing?

**Comment by bzumby** [comment]
> A success template was recently added in #239 - does this cover something else I might be missing?
portfolio_view
vs
portfolio_view

Case:

```
WF:
  jobs:
    - job1
    - job2
    - notify-workflow-success:
      requires:
        - job1
        - job2

jobs:
  job1:
    - run: hello
    - notify-job-fail
  job1:
    - run: hello
    - notify-job-fail
  workflow-status:
    - run: hello
    - notify-workflow-success
        
```

If any job from WF fails - you get **job fail** notification with _job related info_
If the whole workflow (all jobs) are successful - you get **workflow success** notification with the _info related to whole workflow_ 

You **dont** need the info about **notify-workflow-success** job (which will happen if you use _basic_job_success_ template  in **workflow-status** job

**Comment by dsayling** [comment]
I guess I see the distinction, but I think I'm going to let the de-facto owner of the orb make the final call, @KyleTryon ?

**Comment by bzumby** [comment]
Closing this, got resolved by using custom orb :)

**Pull request closed without merging**
