### PR TITLE
Copy include_* options from notify to status => master

### PR DESCRIPTION
**Pull request by iynere**
https://github.com/CircleCI-Public/slack-orb/pull/36

### CODE REVIEW

**Comment by iynere** [comment]
@stig let's chat about your PR here now

the notifications all look good on our end, but the tests just use the default parameters, which i think don't actually test the changes you enabled

**Comment by iynere** [comment]
Screen Shot 2019-03-29 at 5 59 32 PM

@stig how's that look to you ? regular version, with default values, up top; one-liner, with those values set to false, below

looks good to me ! @KyleTryon thoughts ?

**Comment by stig** [comment]
@iynere That looks perfect!

**Comment by stig** [comment]
@iynere I didn't find any tests previously, but I think you're referring to the circleci jobs & workflows, right? I can try to add some to test these changes if you want?

**Comment by iynere** [comment]
@stig ya exactly, not 'tests' per-se, but just simple usage-based integration tests reality-checking that things do what you expect them to do 👌 

see write-up here: https://circleci.com/blog/creating-automated-build-test-and-deploy-workflows-for-orbs-part-2

**Comment by iynere** [comment]
oh, i forgot lol, i actually already added them @stig https://github.com/CircleCI-Public/slack-orb/pull/38/commits/b79b8b9d330ea1b237d8d7b4fc4a0de71f7af573

i'll merge this :)

**Pull request merged**
