### PR TITLE
Handle CIRCLE_TAG not being set

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Following up from #259

### CODE REVIEW

**Review by KyleTryon — DISMISSED** [review]
Thank you

**Comment by KyleTryon** [comment]
@brandon-leapyear Could I bother you to add it to the branch as well while we are here?

**Comment by brandon-leapyear** [comment]
done

**Review by KyleTryon — APPROVED** [review]
Much appreciated

**Comment by KyleTryon** [comment]
Thank you @brandon-leapyear. Merging now, the update will be live in a moment.

**Pull request merged**
