### PR TITLE
Add a success_only parameter

### PR DESCRIPTION
**Pull request by blordpluto**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Our use case is that we are doing multiple flavored deploys from a single repo. If there is a build or deploy failure, we want to message a Slack channel for the devs to fix it. fail_only works for that. Devs don't need to be bothered if there is no error. Great.

But if there is a successful deploy, we want to notify the testing and reliability people, in a different channel. BUT the testers don't care about failures. They only want to know when something new has successfully been deployed. And there is a lot of volume so controlling noise is important.

See my earlier request at issue https://github.com/CircleCI-Public/slack-orb/issues/133.

### Description

The new `success_only` parameter in this PR is very similar to the current `fail_only` parameter, just with the logic inverted.

### CODE REVIEW

**Comment by KyleTryon** [comment]
I think this is a valid use-case but I would vote to remove the `notify-on-success` command. The `notify` command can handle this with the parameter as you have added, and the notify command could be called twice if desired (just supply a custom `name` parameter).

Thank you.

**Comment by blordpluto** [comment]
@KyleTryon Thanks for the quick feedback. Please let me know if this change ^^^ works for you.

**Comment by KyleTryon** [comment]
Much appreciated. Merging in 🎉

**Comment by blordpluto** [comment]
Great! 🙌  Can I ask when we might expect a 3.4.3 release that includes this?

**Pull request merged**
